// This file will be overwritten by Supabase CLI type generation.
// Refer to the project's README or type generation scripts for more info.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Placeholder until types are generated. 
// Replace with the actual Database interface generated by Supabase.
export interface Database {
  public: {
    Tables: {};
    Views: {};
    Functions: {};
  };
}